---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore

test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore