---
# Name your file secrets.yml

development:
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore

test:
  DB_FILENAME:    app/infrastructure/database/local/test.db
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore

production:
  # Assign DATABASE_URL in production
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore