---
# Name your file secrets.yml

development:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: soa-codepraise-clone-dev
  CLONE_QUEUE_URL: <set by AWS>
  REPORT_QUEUE: codepraise-report-development
  REPORT_QUEUE_URL: <set by AWS

app_test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-test
  CLONE_QUEUE_URL: <set by AWS>
  REPORT_QUEUE: codepraise-report-test
  REPORT_QUEUE_URL: <set by AWS

test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-test
  CLONE_QUEUE_URL: <set by AWS>
  REPORT_QUEUE: codepraise-report-test
  REPORT_QUEUE_URL: <set by AWS

production:
  API_HOST: http://localhost:9090
  # Infrastructure
  # - assign DATABASE_URL in production
  GITHUB_TOKEN:   create_github_token
  REPOSTORE_PATH: app/infrastructure/git/repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-production
  CLONE_QUEUE_URL: <set by AWS>
  REPORT_QUEUE: codepraise-report-production
  REPORT_QUEUE_URL: <set by AWS